### ISSUE TITLE
4h - Level editor tweaks

### ISSUE THREAD

**Issue by RileyA** [RileyA/STATICly-MAD#14]
Various improvements for usability's sake, snapping to a grid, constraining drag/scale to a single axis, misc bugfixes, etc.

**Comment by Craig-Macomber** [comment]
Bug: Blocks often move when setting their properties.

Thought: Tracks should have 3 degrees of freedom, and they have 4. What if the line between the ends does not pass through the block? There is clearly an issue that needs clarifying here.

Feature: Some way yo control draw oder. Maybe hold some key and click to send a block back in the ordering.
