### ISSUE TITLE
Editor Bug: Reset Crashes editor

### ISSUE THREAD

**Issue by Craig-Macomber** [RileyA/STATICly-MAD#45]
Resetting a level causes this:
(testing levels is very hard now)

TypeError: Error #1009: Cannot access a property or method of a null object reference.
    at Editor::BlockProxy/reposition()
    at Editor::EditorState/doReset()
    at Editor::EditorState/update()
    at Game/update()
    at EditorMain/update()

To reproduce:
Load any level containing a surface element or a free block, hit "R".

Does not effect:
levels where you added surface elements instead of loading them
action elements

**Comment by RileyA** [comment]
Fixed.
