### ISSUE TITLE
1h - Carpet sometimes doesn't charge

### ISSUE THREAD

**Issue by djmailhot** [RileyA/STATICly-MAD#5]
Usually ofter transferring charge

**Comment by Craig-Macomber** [comment]
This was pissing me off, and making level testing hard, so I fixed it.

**Comment by djmailhot** [comment]
Shoot, okay sorry I didn't get to it earlier.

What was the problem?

~>David

On 2 May 2012 00:59, Craig <
reply@reply.github.com
